
version: 0.2

phases:
  install:
    commands:
      - "apt install unzip -y"
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - "unzip -o terraform.zip"
      - "mv terraform /usr/local/bin"

  pre_build:
    commands:
      - terraform init    

  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR"
      - terraform $TF_COMMAND -auto-approve

  post_build:
    commands:
      - echo "Terraform $TF_COMMAND completed on `date`"

